language: node_js
node_js:
  - '6.3.0'
os:
  - linux
  - osx
matrix:
  fast_finish: true
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
    fi
script:
  - npm run dev-release
  - npm run cucumber
  - npm test
deploy:
  provider: releases
  api_key:
    secure: oPM+h7l9R0rE2OJ6o8h62xs7FuyIha/10MZlduuyI+3UAdRCUMzUsX03bdQa2xiaGvHiUtEvy4OgUnu73VRhIktx4HtvUfRVG7XLEahK5caq8eimqID+dtkHtjxniV23hQSsINap16lIj2Zo8xspzEUQhUW2ax5xWKCDhaCr70qdziasybHSXuPZdCnGpYYa7CD24rjH3/IEJETb9JuTPvtRLvyyGxY8UyYwTnKdSXV1ZGD1YN+vvNaI9bT1FM2BxYErrYOH/QsR9i9HdzaFmvBxwQY5/weyZHLAq945rMAIr2Or8add88dxXHYRmSufAqxJoZc2dmlnyl7QTpVlSCh3jHwLl5+JuZzKqSS43AFHSwIxlhzuaO12l7eFAbqOGwC98Kp6mN00KCylMpwn7zCKmx8RcPAbdBcbQLvKvcbLZ5orw7ExhXP0Jgmd6FVp6tqzYQ8B+wxfi3FT04kGZUpYNKJFsXo6rMc3+v56jhmhS5KIpe+KCm6yUcoIm2LH8L1Zr2i57AOfZGbNXT7bjwab2em9CIZM0h4hPJ8Vm8w3vdi+gLjy4OgZGbnuZCh7ZX/Ei/hyHfWvdJJZgiuWkqyXDBX3j6TxN3MlIZuZv0AVRaMbdGp9qXClmqvA4dBr7fVhKHS5l+BfCq1fOYUjxwKHYALf590rzuIRg5/0i/M=
  file: "releases/*"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: tinytacoteam/zazu
