language: ruby

rvm:
  - 2.2

cache: bundler

branches:
  only:
    - gh-pages

before_install:
  - npm install -g markdown-spellcheck
  - gem install jekyll:3.1.2 html-proofer

script:
  - mdspell -nar --en-us "**/*.md" "!**/vendor/**/*.md"
  - jekyll build
  - htmlproofer ./_site
