# Site settings
title: Zazu App
description: >
  Zazu is a new open source productivity app, that allows developers to be in the
  drivers seat. Unlike other solutions, there is no built in integrations, so
  every plugin has the full scope of what Zazu has to offer.
fixedNav: 'true' # true or false
theme: mint # teal, purple, green, blue, orange, purple, grey
siteurl: 'http://zazuapp.org'
branch: gh-pages

collections:
  packages:
    output: false
  documentation:
    output: true
    permalink: /documentation/:path/

gems:
  - jekyll-github-metadata
  - kramdown
  - rouge

# Social
twitterUsername:
dribbbleUsername:
codepenUsername:
githubUsername: tinytacoteam

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages, _packages, _documentation]
exclude: [vendor, _site, CHANGELOG.md, LICENSE, README.md, .ruby-version]
sass:
  style: compressed
currentCommitSha: 0e8833fbf500e11b8ded07d37999a3dfb65178c7

currentAppVersion: v0.1.2
