# Site settings
title: Zazu App
description: >
  Zazu is a new open source productivity app, that allows developers to be in the
  drivers seat. Unlike other solutions, there is no built in integrations, so
  every plugin has the full scope of what Zazu has to offer.
fixedNav: 'true' # true or false
theme: mint # teal, purple, green, blue, orange, purple, grey
siteurl: 'http://zazuapp.org'
branch: gh-pages

collections:
  tutorials:
    output: true
    permalink: /tutorials/:path/
  packages:
    output: false
  documentation:
    output: true
    permalink: /documentation/:path/

gems:
  - jekyll-github-metadata
  - kramdown
  - rouge

# Social
twitterUsername:
dribbbleUsername:
codepenUsername:
githubUsername: tinytacoteam

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages, _tutorials, _packages, _documentation]
exclude: [vendor, _site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
currentCommitSha: 9acfa4b6bc43248b819d530378f6e9933dbe6db4
