environment:
  nodejs_version: "6"

os: unstable

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:Path += ";C:\Program Files (x86)\NSIS"
  - choco install nsis -pre -y
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run dev-release
  - npm run cucumber
  - npm test

artifacts:
  - path: releases\*.exe
    name: ZazuWin

deploy:
  provider: GitHub
  auth_token:
    secure: XJXnzo2BTOVQ/JOyd7ccmoVhucZbl3lEzeKACXgROih54K5JZKGIjAdx1pAX/E+G
  artifact: ZazuWin
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

build: off
